defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "/testrepo"
images:
  warning: "![Warning](/testrepo/images/warning.png)"
  example: "![Example](/testrepo/images/document-info.png)"
headers:
  exampleWebservice: "Direct webservice call"
  exampleAPI: "Webservice call via API.dll"
  request: "![Request](/testrepo/images/server-import.png) Request"
  response: "![Response](/testrepo/images/server-export.png) Response"
sections:
  beginExampleWebService: "<fieldset><legend> {{site.headers['exampleWebservice']}} </legend>"
  beginExampleAPI: "<fieldset><legend> {{site.headers['exampleAPI']}} </legend>"
  endExample: "</fieldset>"
gems:
  - jekyll-redirect-from
