defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: /testrepo
category-list: [
  General Information, 
  ServiceInformation, 
  Configuration, 
  Catalogues, 
  Parts, 
  Characteristics, 
  Measurements, 
  Measured Values, 
  Raw Data
]
