defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "http://pegasus.windowsphonewelt.de"
links:
  configuration: "[Configuration](/dataservice/configuration/)"
images:
  warning: "![Warning](/images/warning.png)"
  info: "![Info](/images/info.png)"
  parameter: "![Info](/images/parameter.png)"
  parameter16: "![Info](/images/parameter_16.png)"
  returnParameter: "![Info](/images/returnParameter.png)"
  returnParameter16: "![Info](/images/returnParameter_16.png)"
  summary: "![Info](/images/summary.png)"
  summary16: "![Info](/images/summary_16.png)"
  list-info: "![List Info](/images/list-info.png)"
  document-info: "![Document Info](/images/document-info.png)"
  example16: "![Example](/images/example_16.png)"
  function-get: "![Get](/images/function-get.png)"
  function-create: "![Create](/images/function-create.png)"
  function-update: "![Update](/images/function-update.png)"
  function-delete: "![Delete](/images/function-delete.png)"
sections:
  getLabel: <span class="label label-primary">GET</span>
  postLabel: <span class="label label-success">POST</span>
  putLabel: <span class="label label-warning">PUT</span>
  deleteLabel: <span class="label label-danger">DELETE</span>
headers:
  example: "##### ![Example](/images/document-info.png) Example: "
  request: "##### Request"
  response: "##### Response"
gems:
  - jekyll-redirect-from
