defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "/testrepo"
links:
  configuration: "[Configuration](/testrepo/dataservice/configuration/)"
images:
  warning: "![Warning](/testrepo/images/warning.png)"
  info: "![Info](/testrepo/images/info.png)"
  parameter: "![Info](/testrepo/images/parameter.png)"
  parameter16: "![Info](/testrepo/images/parameter_16.png)"
  returnParameter: "![Info](/testrepo/images/returnParameter.png)"
  returnParameter16: "![Info](/testrepo/images/returnParameter_16.png)"
  summary: "![Info](/testrepo/images/summary.png)"
  summary16: "![Info](/testrepo/images/summary_16.png)"
  list-info: "![List Info](/testrepo/images/list-info.png)"
  document-info: "![Document Info](/testrepo/images/document-info.png)"
  example16: "![Example](/testrepo/images/example_16.png)"
  function-get: "![Get](/testrepo/images/function-get.png)"
  function-create: "![Create](/testrepo/images/function-create.png)"
  function-update: "![Update](/testrepo/images/function-update.png)"
  function-delete: "![Delete](/testrepo/images/function-delete.png)"
headers:
  example: "##### ![Example](/testrepo/images/document-info.png) Example: "
  request: "##### Request"
  response: "##### Response"
sections:
  beginExampleWebService: "<fieldset><legend><span><img src=\"/testrepo/images/document-info.png\"/></span> Example:</legend>"
  beginExampleAPI: "<fieldset><legend> Webservice call via API.dll </legend>"
  endExample: "</fieldset>"
  endCode: "</div>"
settings:
  defaultCodeFormat: "json"
gems:
  - jekyll-redirect-from
