defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "/testrepo"
images:
  warning: "![Warning](/testrepo/images/warning.png)"
headers:
  exampleWebservice: "![Request](/testrepo/images/server-import.png) Direct webservice call"
gems:
  - jekyll-redirect-from
