defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "/testrepo"
images:
  warning: "![Warning](/testrepo/images/warning.png)"
headers:
  example: "![Example](/testrepo/images/document-info.png) Example:"
  request: "![Request](/testrepo/images/server-import.png) Request"
  response: "![Response](/testrepo/images/server-export.png) Response"
sections:
  beginExampleWebService: "<fieldset><legend> Direct webservice call </legend>"
  beginExampleAPI: "<fieldset><legend> Webservice call via API.dll </legend>"
  endExample: "</fieldset>"
links:
  linkToParameters: "[URL-Parameter section]({{site.baseurl | markdownify }}/general/#{{ page.subCategory | markdownify }})"
gems:
  - jekyll-redirect-from
